version: "3.9"
services:
  auth:
    image: rinp/auth
    depends_on:
      - redis
    container_name: auth
    ports:
      - "8090:8090"
    command:
      - "serve"
      - "--http=0.0.0.0:8090"
    volumes:
      - ./pb_data:/pb_data