FROM debian

# Change mirror
RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list

RUN apt-get update

# Since it is only used in development, seperate the install commands to make use of build caches.
RUN apt-get install -y iproute2
RUN apt-get install -y net-tools
RUN apt-get install -y iputils-ping
RUN apt-get install -y bash
RUN apt-get install -y tcpdump
RUN apt-get install -y iperf3
RUN apt-get install -y curl
