FROM debian

# Change mirror
RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list

RUN apt-get update

RUN apt-get install -y \
    iproute2 \
    net-tools \
    iputils-ping \
    bash \
    iperf3 \
    curl