FROM debian

# Change mirror
RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list && \
    apt-get update

RUN DEBIAN_FRONTEND=noninteractive             \
    apt-get install -y --no-install-recommends \
    iproute2     \
    net-tools    \
    iputils-ping \
    bash         \
    tcpdump      \
    iperf3       \
    curl