version: "3.9"
services:
  user:
    image: rinp/client  
    depends_on:
      - auth
      - service
      - scheduler
      - proxy1
      - proxy2
      - proxy3
#    command:
#      - "-p=proxy1"
    container_name: user
    privileged: true
    networks:
      rinp-public:
        ipv4_address: 172.127.1.10

  auth:
    image: rinp/auth   
    container_name: auth
    ports:
      - "8090:8090"
    command: ["serve","--http=0.0.0.0:8090"]
    volumes:
      - ./pb_data:/pb_data
    networks:
      rinp-public:
        ipv4_address: 172.127.1.101
      rinp-private:
        ipv4_address: 172.127.2.101

  proxy1:
    image: rinp/proxy
    container_name: proxy1
    depends_on:
      - redis
    command:
      - "--redis=redis:6379"
      - "--name=proxy1"
      - "--public-ip=proxy1"
      - "--log-level=debug"
    networks:
      rinp-public:
        ipv4_address: 172.127.1.111
      rinp-private:
        ipv4_address: 172.127.2.111
  proxy2:
    image: rinp/proxy
    container_name: proxy2
    depends_on:
      - redis
    command:
      - "--redis=redis:6379"
      - "--name=proxy2"
      - "--public-ip=proxy2"
    networks:
      rinp-public:
        ipv4_address: 172.127.1.112
      rinp-private:
        ipv4_address: 172.127.2.112
  proxy3:
    image: rinp/proxy
    container_name: proxy3
    depends_on:
      - redis
    command:
      - "--redis=redis:6379"
      - "--name=proxy3"
      - "--public-ip=proxy3"
    networks:
      rinp-public:
        ipv4_address: 172.127.1.113
      rinp-private:
        ipv4_address: 172.127.2.113

  service:
    image: rinp/sidecar
    container_name: service
    depends_on:
      - redis
    command:
       - "-c=7.0.0.0/8"
       - "-p=12345"
       - "-s=11.22.33.44"
       - "--public-ip=service"
       - "--redis=redis:6379"
    privileged: true
    networks:
      rinp-private:
        ipv4_address: 172.127.2.201

  scheduler-sidecar:
    image: rinp/sidecar
    container_name: scheduler-sidecar
    depends_on:
      - redis
      - scheduler
    command:
      - "-c=7.0.0.0/8"
      - "-p=12345"
      - "-s=11.22.33.55"
      - "--public-ip=scheduler"
      - "--redis=redis:6379"
    privileged: true
    network_mode: service:scheduler
#    networks:
#      rinp-private:
#        ipv4_address: 172.127.2.202

  scheduler:
    # Virtual IP 11.22.33.55 
    image: rinp/scheduler
    container_name: scheduler
    depends_on:
      - redis
    command:
      - "--log-level=debug"
      - "--redis=redis:6379"
    privileged: true
    networks:
      rinp-private:
        ipv4_address: 172.127.2.202

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      rinp-private:
        ipv4_address: 172.127.2.220

networks:
  rinp-public:
    driver: bridge
    ipam:
      config:
        - subnet: 172.127.1.0/24
  rinp-private:
    driver: bridge
    ipam:
      config:
        - subnet: 172.127.2.0/24
