apiVersion: apps/v1
kind: Deployment
metadata:
  name: rinp-controller
  namespace: rinp-system
  labels:
    control-plane: rinp-controller
spec:
  selector:
    matchLabels:
      control-plane: rinp-controller
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: rinp-controller
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - command:
            - /controller
          args:
            - --leader-elect
            - --create-default-instance
            - --service-use-default-instance
          image: rinp/controller:latest
          name: controller
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          # TODO(user): Configure the resources accordingly based on the project requirements.
          # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
      serviceAccountName: rinp-controller
      terminationGracePeriodSeconds: 10
