---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: rinp-controller-role
rules:
- apiGroups:
  - rinp.narc.bupt.edu.cn
  resources:
  - proxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rinp.narc.bupt.edu.cn
  resources:
  - proxies/finalizers
  verbs:
  - update
- apiGroups:
  - rinp.narc.bupt.edu.cn
  resources:
  - proxies/status
  verbs:
  - get
  - patch
  - update
